"""add interested_in_products

Revision ID: 3eecceb14941
Revises: 2b2260d226a2
Create Date: 2026-06-11 09:23:53.278334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eecceb14941'
down_revision: Union[str, Sequence[str], None] = '2b2260d226a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ev_leads', sa.Column('interested_in_products', sa.String(), nullable=True))
    op.add_column('insurance_leads', sa.Column('bike_insurance', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.drop_column('insurance_leads', 'bike_insurance')
    op.drop_column('ev_leads', 'interested_in_products')
    # ### end Alembic commands ###
